# Project
version=2.7.4
group=io.github.sycamore0
java_version=25

# Common
minecraft_version=26.1
mod_name=MyLuckyBlock
mod_author=Sycamore0,aL1sia
mod_id=myluckyblock
license=MIT
credits=
description=Add a lucky block to Minecraft 1.21+ that players can break to trigger random events.
minecraft_version_range=(1.21.11, 26.5]

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Fabric
fabric_version=0.144.1+26.1
fabric_loader_version=0.18.4

# NeoForge
neoforge_version=26.1.2.68-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
